[2022-06-07 04:32:10,392] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: my_first_dag.print_whoami 2022-06-06T00:00:00+00:00 [queued]>
[2022-06-07 04:32:10,400] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: my_first_dag.print_whoami 2022-06-06T00:00:00+00:00 [queued]>
[2022-06-07 04:32:10,400] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 04:32:10,400] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-06-07 04:32:10,401] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 04:32:10,409] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): print_whoami> on 2022-06-06T00:00:00+00:00
[2022-06-07 04:32:10,414] {standard_task_runner.py:52} INFO - Started process 1775 to run task
[2022-06-07 04:32:10,417] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'print_whoami', '2022-06-06T00:00:00+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpt0bb1yaw', '--error-file', '/tmp/tmpmr3rmz41']
[2022-06-07 04:32:10,417] {standard_task_runner.py:77} INFO - Job 8: Subtask print_whoami
[2022-06-07 04:32:10,516] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag.print_whoami 2022-06-06T00:00:00+00:00 [running]> on host 6e7d0d9f14a6
[2022-06-07 04:32:10,581] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=jovyan
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=print_whoami
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T00:00:00+00:00
[2022-06-07 04:32:10,582] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-06-07 04:32:10,582] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'whoami']
[2022-06-07 04:32:10,641] {subprocess.py:75} INFO - Output:
[2022-06-07 04:32:10,643] {subprocess.py:79} INFO - default
[2022-06-07 04:32:10,643] {subprocess.py:83} INFO - Command exited with return code 0
[2022-06-07 04:32:10,693] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=print_whoami, execution_date=20220606T000000, start_date=20220607T043210, end_date=20220607T043210
[2022-06-07 04:32:10,724] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-07 04:32:10,787] {local_task_job.py:151} INFO - Task exited with return code 0
